<a href="https://colab.research.google.com/github/dtg-ca/DataScience-the-journey-begins/blob/master/NLP_tf_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)

2.6.0


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
from tensorflow.keras.layers import Input,SimpleRNN,Dense,Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import SGD, Adam

In [4]:
x = np.random.randn(1,3,5)
x

array([[[-0.35259597, -0.94353924, -0.17276629,  1.32714757,
          0.93922447],
        [-2.23122387,  1.04491917, -1.24386436,  0.08866162,
         -1.68104961],
        [ 0.75813034, -0.17022831, -2.03100899,  1.34653874,
         -0.80845012]]])

In [19]:
N = 3
T = 10
D = 3
K = 2
X = np.random.randn(N, T, D)

In [20]:
M = 5
i = Input(shape = (T,D))
x = SimpleRNN(M)(i)
x = Dense(K)(x)
model = Model(i, x)

In [21]:
Yhat = model.predict(X)
print(Yhat), Yhat.shape

[[-0.27688962 -0.21762127]
 [-0.36972883  0.01276474]
 [ 0.91572547 -0.31455   ]]


(None, (3, 2))

In [22]:
model.summary()

Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, 10, 3)]           0         
_________________________________________________________________
simple_rnn_2 (SimpleRNN)     (None, 5)                 45        
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 12        
Total params: 57
Trainable params: 57
Non-trainable params: 0
_________________________________________________________________


In [23]:
model.layers[1].get_weights()

[array([[-0.8643438 ,  0.355532  ,  0.54011995,  0.27587396,  0.534576  ],
        [-0.6776891 ,  0.502389  , -0.05873042,  0.7004878 ,  0.70981497],
        [ 0.10971874, -0.6457157 ,  0.39609927, -0.5023452 ,  0.799154  ]],
       dtype=float32),
 array([[ 0.2673428 ,  0.68627113, -0.44664103,  0.50690085, -0.03351386],
        [-0.8667022 , -0.00326573, -0.45186114,  0.07640459,  0.196978  ],
        [-0.41190168,  0.41953352,  0.5442859 ,  0.08971736, -0.59163517],
        [ 0.08110937,  0.07604201, -0.5114762 , -0.6340353 , -0.5692364 ],
        [ 0.03336583, -0.58926284, -0.19615805,  0.5719824 , -0.53480303]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [24]:
a, b, c = model.layers[1].get_weights()
print(a.shape, b.shape, c.shape)

(3, 5) (5, 5) (5,)


In [25]:
Wx, Wh, bh = model.layers[1].get_weights()
Wo, bo = model.layers[2].get_weights()

In [30]:
h_last = np.zeros(M)
x = X[0]
Yhats = []

for t in range(T):
  h = np.tanh(x[t].dot(Wx) + h_last.dot(Wh) + bh)
  y = h.dot(Wo) + bo
  Yhats.append(y)

  h_last = h
print(Yhats[-1])

[-0.27688972 -0.21762126]
